Feat:AutoLogin
theproductiveprogrammer/desktop-avatar pull request #10
Opened 2021-06-17 16:23 UTC by Bibitha-V

2021-06-19 02:00 UTC, theproductiveprogrammer requested changes

2021-06-20 18:19 UTC, Bibitha-V commented on login.js
> +            login_json=  fs.readFileSync(path.join(loc.home(),"logininfo.json"),"utf-8", (err, data) => {
updated with readFile method

2021-06-20 18:20 UTC, Bibitha-V commented on web/login.js
> +        alert("auto Login failed")
updated

2021-06-20 18:20 UTC, Bibitha-V commented on web/login.js
> +        alert("auto Login failed")
here also updated the same

2021-06-20 18:21 UTC, Bibitha-V commented on web/main.js
> +          document.body.firstElementChild.remove()
removed by using id

2021-06-20 18:21 UTC, Bibitha-V commented on web/main.js
> +          result=JSON.parse(result)
handled in getLoginInfo

2021-06-21 00:00 UTC, theproductiveprogrammer commented on index.js
> +      return JSON.parse(result);
JSON.parse should always be wrapped in a try-catch block because it can throw errors

2021-06-21 00:06 UTC, theproductiveprogrammer commented on index.js
> +      return JSON.parse(result);
Also the JSON.parse is better done within getUserLoginInfo (login info should be the actual info not a string that we need to parse after)

2021-06-21 02:57 UTC, Bibitha-V commented on index.js
> +      return JSON.parse(result);
updated the code

2021-06-21 03:57 UTC, theproductiveprogrammer approved these changes

2021-06-21 03:57 UTC, merged