Added limit and left for tasks
theproductiveprogrammer/desktop-avatar pull request #32
Opened 2021-08-09 04:39 UTC by Bibitha-V

2021-08-12 22:26 UTC, theproductiveprogrammer requested changes

2021-08-12 22:26 UTC, theproductiveprogrammer commented on web/engine/data.js
> +    }
This could have been done earlier. The number of steps seems to be a bit too many

2021-08-12 22:26 UTC, theproductiveprogrammer commented on web/engine/data.js
> +
# Sample Rewrite FYI & Reference

Try using/rewriting like this

```javascript
/*    problem/
 * return a summary of the number of tasks performed, grouped
 * by task type (action)
 *
 *    understand/
 * The DB data is stored in a per-user, per-task format with each task update listed in it's "steps" field:
 *    {
 *      userid: {
 *        id1: {
 *          ...
 *          steps: {
 *            { t: "2020-11-02T05:01:13.592Z", e: "task/new", data: { action: "LINKEDIN_VIEW" ...} ...},
 *            { t: "....", e: "task/status" data: { msg: "task/done", code: 200 ...} ... },
 *            { t: "....", e: "task/status" data: { msg: "task/completed", code: 202 ...} ... },
 *            { ... task update ...},
 *            { ... task update ...},
 *          }
 *        },
 *        id2: ...,
 *        id3: ...,
 *      }
 *
 *    way/
 * Walk the steps and count those completed within the last 24
 * hours against that task action.
 */
function getTasksPerDay(userid) {
  const tasksDoneToday = {}

  const tasks = DB[userid]
  if(!tasks) return tasksDoneToday

  const currentTime = Date.now()
  for(const task in tasks) {
    let current_action = null
    task.steps.map(t => {
      if(t.data.action) current_action = t.data.action
      if(!tasksDoneToday[current_action]) tasksDoneToday[current_action] = 0
      if(t.data.code != 202) return
      const tt = (new Date(t.t)).getTime()
      const hours = Math.floor((currentTime - tt) / 3600000);
      if(hours < 24) tasksDoneToday[current_action] += 1
    })
  }
  return tasksDoneToday
}
```

Note that the function is much smaller and simpler. We would probably want to make it more resilient by adding error checks:

```javascript
function getTasksPerDay(userid) {
  const tasksDoneToday = {}

  const tasks = DB[userid]
  if(!tasks) return tasksDoneToday

  const currentTime = Date.now()
  for(const task in tasks) {
    let current_action = null
    task.steps.map(t => {
      if(!t.data) return
      if(t.data.action) current_action = t.data.action
      if(!current_action) return
      if(!tasksDoneToday[current_action]) tasksDoneToday[current_action] = 0
      if(t.data.code != 202) return
      if(!t.t) return
      const tt = (new Date(t.t)).getTime()
      const hours = Math.floor((currentTime - tt) / 3600000);
      if(hours < 24) tasksDoneToday[current_action] += 1
    })
  }
  return tasksDoneToday
}
```

2021-08-13 13:52 UTC, Bibitha-V commented on web/engine/data.js
> +    let [...taskArr] = tasks;
I was trying the array approach for looping

2021-08-13 13:53 UTC, Bibitha-V commented on web/engine/data.js
> +    let taskType = taskArr.map((task) => {
incorrect naming convention

2021-08-13 13:56 UTC, Bibitha-V commented on web/engine/data.js
> +    let finalObj = taskType.map((el) => {
attempt summary

2021-08-13 13:56 UTC, Bibitha-V commented on web/engine/data.js
> +    }
updated as per the review comments

2021-08-13 22:16 UTC, theproductiveprogrammer approved these changes

2021-08-13 22:16 UTC, merged